---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - operatorgroup.yaml
  - subscription.yaml
  - multiclusterengine.yaml
  - ManagedCluster.yaml
  - ManagedClusterAddOn.yam

namespace: multicluster-engine
